# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-upvote']},
        ),
    ]
