# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171112_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='author',
            new_name='user',
        ),
    ]
