# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
