# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20171113_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'picture', 'verbose_name_plural': 'pictures'},
        ),
    ]
