# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20171116_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
