# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20171118_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
