# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_picture_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='profile',
        ),
    ]
