# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20171125_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
